In [1]:
import pandas as pd 
import numpy as np
import unicodedata

In [2]:
cd C:/Users/Marcus/Desktop/python/alf_sports_betting_predictor/data/

C:\Users\Marcus\Desktop\python\alf_sports_betting_predictor\data

In [3]:
ls

 Volume in drive C has no label.
 Volume Serial Number is F66A-C1F7

 Directory of C:\Users\Marcus\Desktop\python\alf_sports_betting_predictor\data

22/03/2021  06:48 PM    <DIR>          .
22/03/2021  06:48 PM    <DIR>          ..
22/03/2021  06:08 PM    <DIR>          .ipynb_checkpoints
22/03/2021  05:52 PM            20,125 20210317 AFL_2020_fixture_edited.csv
22/03/2021  06:47 PM            13,000 20210317 AFL_2020_stats_win_loss_normalised.csv
22/03/2021  06:36 PM             2,023 20210317 afl_2020_team_stats.csv
22/03/2021  06:36 PM            24,185 20210322 AFL_2020_team_stats_and_win_loss.csv
22/03/2021  06:36 PM             4,854 20210322 AFL_2020_team_stats_and_win_loss_trimmed.csv
22/03/2021  06:08 PM           134,507 Untitled.ipynb
22/03/2021  06:07 PM                72 Untitled1.ipynb
22/03/2021  06:48 PM            20,994 Untitled2.ipynb
               8 File(s)        219,760 bytes
               3 Dir(s)  1,892,170,272,768 bytes free

In [4]:
df = pd.read_csv('20210317 afl_2020_team_stats.csv')
df_team = pd.read_csv('20210317 AFL_2020_fixture_edited.csv')

In [5]:
df.columns

Index(['Team Totals For��', 'KI�?', 'MK��', 'HB��', 'DI��', 'GL��', 'BH��',
       'HO��', 'TK��', 'RB��', 'IF��', 'CL��', 'CG��', 'FF��', 'BR��', 'CP��',
       'UP��', 'CM��', 'MI��', '1%��', 'BO��', 'GA��'],
      dtype='object')

In [6]:
df['Team Totals For��']

0              Geelong
1             Richmond
2             Brisbane
3        Port Adelaide
4             St Kilda
5          Collingwood
6           West Coast
7              Carlton
8     Western Bulldogs
9                  GWS
10          Gold Coast
11           Fremantle
12              Sydney
13           Melbourne
14            Essendon
15     North Melbourne
16            Hawthorn
17            Adelaide
18              Totals
Name: Team Totals For��, dtype: object

In [7]:
def normalise_data(df, column):
    df[column + '_normalised'] = (df[column] - df[column].min()) / (df[column].max() - df[column].min())
    return df

In [8]:
df['Team'] = df['Team Totals For��']
df['kicks'] = df['KI�?']
df['1%s'] = df['1%��']

In [9]:
df

,Team Totals For��,KI�?,MK��,HB��,DI��,GL��,BH��,HO��,TK��,RB��,...,CP��,UP��,CM��,MI��,1%��,BO��,GA��,Team,kicks,1%s
0,Geelong,3976,1757,2542,6518,220,146,626,1092,625,...,2540,3919,190,224,897,42,169,Geelong,3976,897
1,Richmond,3587,1437,2507,6094,202,133,557,1077,650,...,2436,3569,184,202,862,130,138,Richmond,3587,862
2,Brisbane,3444,1437,1865,5309,181,175,584,986,590,...,2246,2973,188,184,801,30,114,Brisbane,3444,801
3,Port Adelaide,3444,1260,2421,5865,183,151,567,1086,537,...,2408,3397,171,161,872,46,122,Port Adelaide,3444,872
4,St Kilda,3438,1427,2118,5556,187,123,612,904,589,...,2190,3273,182,175,764,92,113,St Kilda,3438,764
5,Collingwood,3301,1345,2684,5985,156,98,688,967,520,...,2298,3652,167,133,819,52,101,Collingwood,3301,819
6,West Coast,3283,1418,1871,5154,173,107,636,820,584,...,2065,3078,190,161,897,50,114,West Coast,3283,897
7,Carlton,3071,1200,1710,4781,146,114,478,899,529,...,2050,2631,171,149,719,56,94,Carlton,3071,719
8,Western Bulldogs,3007,1164,2572,5579,168,128,336,904,533,...,2124,3431,160,169,793,68,109,Western Bulldogs,3007,793
9,GWS,3005,1244,2069,5074,145,105,441,885,574,...,2005,3013,145,136,791,48,101,GWS,3005,791
10,Gold Coast,2990,1140,1864,4854,142,111,534,828,592,...,2017,2736,144,119,685,54,84,Gold Coast,2990,685
11,Fremantle,2975,1231,2124,5099,127,78,494,828,581,...,2029,3027,176,142,718,50,85,Fremantle,2975,718
12,Sydney,2975,1116,2002,4977,128,105,463,936,629,...,2016,2811,151,122,741,47,82,Sydney,2975,741
13,Melbourne,2954,1212,2086,5040,155,114,572,748,527,...,2057,2918,162,155,727,24,108,Melbourne,2954,727
14,Essendon,2854,1121,2286,5140,136,101,447,841,554,...,1892,3108,135,141,708,99,93,Essendon,2854,708
15,North Melbourne,2832,1084,2269,5101,124,86,516,843,578,...,2020,3001,148,124,641,59,85,North Melbourne,2832,641
16,Hawthorn,2794,1122,2106,4900,147,89,499,816,529,...,1871,2954,142,131,758,40,99,Hawthorn,2794,758
17,Adelaide,2661,1006,2140,4801,116,100,536,905,581,...,1940,2774,150,97,641,36,71,Adelaide,2661,641
18,Totals,56591,22721,39236,95827,2836,2064,9586,16365,10302,...,38204,56265,2956,2725,13834,1023,1882,Totals,56591,13834

In [10]:
df = normalise_data(df, 'kicks')
df = normalise_data(df, '1%s')

In [11]:
df

,Team Totals For��,KI�?,MK��,HB��,DI��,GL��,BH��,HO��,TK��,RB��,...,CM��,MI��,1%��,BO��,GA��,Team,kicks,1%s,kicks_normalised,1%s_normalised
0,Geelong,3976,1757,2542,6518,220,146,626,1092,625,...,190,224,897,42,169,Geelong,3976,897,0.024383,0.019404
1,Richmond,3587,1437,2507,6094,202,133,557,1077,650,...,184,202,862,130,138,Richmond,3587,862,0.017170,0.016751
2,Brisbane,3444,1437,1865,5309,181,175,584,986,590,...,188,184,801,30,114,Brisbane,3444,801,0.014519,0.012128
3,Port Adelaide,3444,1260,2421,5865,183,151,567,1086,537,...,171,161,872,46,122,Port Adelaide,3444,872,0.014519,0.017509
4,St Kilda,3438,1427,2118,5556,187,123,612,904,589,...,182,175,764,92,113,St Kilda,3438,764,0.014408,0.009323
5,Collingwood,3301,1345,2684,5985,156,98,688,967,520,...,167,133,819,52,101,Collingwood,3301,819,0.011867,0.013492
6,West Coast,3283,1418,1871,5154,173,107,636,820,584,...,190,161,897,50,114,West Coast,3283,897,0.011533,0.019404
7,Carlton,3071,1200,1710,4781,146,114,478,899,529,...,171,149,719,56,94,Carlton,3071,719,0.007602,0.005912
8,Western Bulldogs,3007,1164,2572,5579,168,128,336,904,533,...,160,169,793,68,109,Western Bulldogs,3007,793,0.006416,0.011521
9,GWS,3005,1244,2069,5074,145,105,441,885,574,...,145,136,791,48,101,GWS,3005,791,0.006379,0.011370
10,Gold Coast,2990,1140,1864,4854,142,111,534,828,592,...,144,119,685,54,84,Gold Coast,2990,685,0.006101,0.003335
11,Fremantle,2975,1231,2124,5099,127,78,494,828,581,...,176,142,718,50,85,Fremantle,2975,718,0.005822,0.005836
12,Sydney,2975,1116,2002,4977,128,105,463,936,629,...,151,122,741,47,82,Sydney,2975,741,0.005822,0.007580
13,Melbourne,2954,1212,2086,5040,155,114,572,748,527,...,162,155,727,24,108,Melbourne,2954,727,0.005433,0.006519
14,Essendon,2854,1121,2286,5140,136,101,447,841,554,...,135,141,708,99,93,Essendon,2854,708,0.003579,0.005078
15,North Melbourne,2832,1084,2269,5101,124,86,516,843,578,...,148,124,641,59,85,North Melbourne,2832,641,0.003171,0.000000
16,Hawthorn,2794,1122,2106,4900,147,89,499,816,529,...,142,131,758,40,99,Hawthorn,2794,758,0.002466,0.008868
17,Adelaide,2661,1006,2140,4801,116,100,536,905,581,...,150,97,641,36,71,Adelaide,2661,641,0.000000,0.000000
18,Totals,56591,22721,39236,95827,2836,2064,9586,16365,10302,...,2956,2725,13834,1023,1882,Totals,56591,13834,1.000000,1.000000

In [12]:
df_team

,Date,Home V Away,Venue,Crowd,Result,Disposals,Goals,score_home,score_away,home_team,away_team,home_win_lose,away_win_lose
0,Â Thu 19 Mar 7:40pm,RichmondÂ vÂ Carlton,MCG,NaN,105-81,P. CrippsÂ 31,J. MartinÂ 4,105,81,Richmond,Carlton,1,0
1,Â Fri 20 Mar 7:50pm,Western BulldogsÂ vÂ Collingwood,Marvel Stadium,NaN,34-86,C. MayneÂ 29,B. MihocekÂ 3,34,86,Western Bulldogs,Collingwood,0,1
2,Â Sat 21 Mar 2:10pm,EssendonÂ vÂ Fremantle,Marvel Stadium,NaN,63-57,D. ShielÂ 35,J. TownsendÂ 3,63,57,Essendon,Fremantle,1,0
3,Â Sat 21 Mar 4:35pm,AdelaideÂ vÂ Sydney,Adelaide Oval,NaN,71-74,L. ParkerÂ 30,I. HeeneyÂ 4,71,74,Adelaide,Sydney,0,1
4,Â Sat 21 Mar 6:40pm,Gold CoastÂ vÂ Port Adelaide,Metricon Stadium,NaN,29-76,T. RockliffÂ 26,S. MotlopÂ 2,29,76,Gold Coast,Port Adelaide,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Â Sat 19 Sep 7:40pm,BrisbaneÂ vÂ Carlton,Gabba,NaN,78-61,S. WalshÂ 31,H. McKayÂ 3,78,61,Brisbane,Carlton,1,0
149,Â Sun 20 Sep 12:35pm,HawthornÂ vÂ Gold Coast,Adelaide Oval,NaN,108-57,T. MitchellÂ 34,J. GunstonÂ 4,108,57,Hawthorn,Gold Coast,1,0
150,Â Sun 20 Sep 3:35pm,SydneyÂ vÂ Geelong,Metricon Stadium,NaN,63-69,J. LloydÂ 27,P. DangerfieldÂ 3,63,69,Sydney,Geelong,0,1
151,Â Sun 20 Sep 6:10pm,FremantleÂ vÂ Western Bulldogs,Cazaly's Stadium,NaN,44-74,L. HunterÂ 35,T. EnglishÂ 2,44,74,Fremantle,Western Bulldogs,0,1
152,Â Mon 21 Sep 7:15pm,CollingwoodÂ vÂ Port Adelaide,Gabba,NaN,45-61,T. RockliffÂ 30,B. MihocekÂ 2,45,61,Collingwood,Port Adelaide,0,1

In [13]:
mask = df_team['away_team'] == 'Carlton'

In [14]:
df_team['away_team'].iloc[0]

'Carlton'

In [15]:
df_team['away_team'].iloc[0].split('a')

['C', 'rlton']

In [16]:
df_team['away_team'] = df_team['away_team'].astype('category')

In [17]:
df_team['away_team'].iloc[0]

'Carlton'

In [18]:
name = ''
for letter in df_team['away_team'].iloc[0]:
    if isinstance(letter, str):
        print(letter)
        name += letter

C
a
r
l
t
o
n

In [19]:
name

'Carlton'

In [20]:
df_team['away_team'].iloc[0].split('0')

['Carlton']

In [21]:
df_team.columns

Index(['Date ', 'Home V Away ', 'Venue ', 'Crowd ', 'Result', 'Disposals',
       'Goals', 'score_home', 'score_away', 'home_team', 'away_team',
       'home_win_lose', 'away_win_lose'],
      dtype='object')

In [22]:
def clean_strings_of_special_characters(df, column):
    for index, row in df.iterrows():
        mask = (df['away_team'] == row['away_team']) & (df['Date '] == row['Date '])
        clean = unicodedata.normalize("NFKD", row['away_team'])
        df.loc[mask, 'away_team_clean'] = clean
    return df

In [23]:
df_team = clean_strings_of_special_characters(df_team, 'away_team')

In [24]:
df_team['away_team_clean'] = df_team['away_team_clean'].str.strip()

In [25]:
df_team['away_team_clean'].iloc[0]

'Carlton'

In [26]:
df_team['away_team'] = df_team['away_team_clean']

In [27]:
df_team.drop(columns=['away_team_clean'], inplace=True)

In [28]:
df_team

,Date,Home V Away,Venue,Crowd,Result,Disposals,Goals,score_home,score_away,home_team,away_team,home_win_lose,away_win_lose
0,Â Thu 19 Mar 7:40pm,RichmondÂ vÂ Carlton,MCG,NaN,105-81,P. CrippsÂ 31,J. MartinÂ 4,105,81,Richmond,Carlton,1,0
1,Â Fri 20 Mar 7:50pm,Western BulldogsÂ vÂ Collingwood,Marvel Stadium,NaN,34-86,C. MayneÂ 29,B. MihocekÂ 3,34,86,Western Bulldogs,Collingwood,0,1
2,Â Sat 21 Mar 2:10pm,EssendonÂ vÂ Fremantle,Marvel Stadium,NaN,63-57,D. ShielÂ 35,J. TownsendÂ 3,63,57,Essendon,Fremantle,1,0
3,Â Sat 21 Mar 4:35pm,AdelaideÂ vÂ Sydney,Adelaide Oval,NaN,71-74,L. ParkerÂ 30,I. HeeneyÂ 4,71,74,Adelaide,Sydney,0,1
4,Â Sat 21 Mar 6:40pm,Gold CoastÂ vÂ Port Adelaide,Metricon Stadium,NaN,29-76,T. RockliffÂ 26,S. MotlopÂ 2,29,76,Gold Coast,Port Adelaide,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Â Sat 19 Sep 7:40pm,BrisbaneÂ vÂ Carlton,Gabba,NaN,78-61,S. WalshÂ 31,H. McKayÂ 3,78,61,Brisbane,Carlton,1,0
149,Â Sun 20 Sep 12:35pm,HawthornÂ vÂ Gold Coast,Adelaide Oval,NaN,108-57,T. MitchellÂ 34,J. GunstonÂ 4,108,57,Hawthorn,Gold Coast,1,0
150,Â Sun 20 Sep 3:35pm,SydneyÂ vÂ Geelong,Metricon Stadium,NaN,63-69,J. LloydÂ 27,P. DangerfieldÂ 3,63,69,Sydney,Geelong,0,1
151,Â Sun 20 Sep 6:10pm,FremantleÂ vÂ Western Bulldogs,Cazaly's Stadium,NaN,44-74,L. HunterÂ 35,T. EnglishÂ 2,44,74,Fremantle,Western Bulldogs,0,1
152,Â Mon 21 Sep 7:15pm,CollingwoodÂ vÂ Port Adelaide,Gabba,NaN,45-61,T. RockliffÂ 30,B. MihocekÂ 2,45,61,Collingwood,Port Adelaide,0,1

In [29]:
# adding team stats to AFL_Fixture csv 
df

,Team Totals For��,KI�?,MK��,HB��,DI��,GL��,BH��,HO��,TK��,RB��,...,CM��,MI��,1%��,BO��,GA��,Team,kicks,1%s,kicks_normalised,1%s_normalised
0,Geelong,3976,1757,2542,6518,220,146,626,1092,625,...,190,224,897,42,169,Geelong,3976,897,0.024383,0.019404
1,Richmond,3587,1437,2507,6094,202,133,557,1077,650,...,184,202,862,130,138,Richmond,3587,862,0.017170,0.016751
2,Brisbane,3444,1437,1865,5309,181,175,584,986,590,...,188,184,801,30,114,Brisbane,3444,801,0.014519,0.012128
3,Port Adelaide,3444,1260,2421,5865,183,151,567,1086,537,...,171,161,872,46,122,Port Adelaide,3444,872,0.014519,0.017509
4,St Kilda,3438,1427,2118,5556,187,123,612,904,589,...,182,175,764,92,113,St Kilda,3438,764,0.014408,0.009323
5,Collingwood,3301,1345,2684,5985,156,98,688,967,520,...,167,133,819,52,101,Collingwood,3301,819,0.011867,0.013492
6,West Coast,3283,1418,1871,5154,173,107,636,820,584,...,190,161,897,50,114,West Coast,3283,897,0.011533,0.019404
7,Carlton,3071,1200,1710,4781,146,114,478,899,529,...,171,149,719,56,94,Carlton,3071,719,0.007602,0.005912
8,Western Bulldogs,3007,1164,2572,5579,168,128,336,904,533,...,160,169,793,68,109,Western Bulldogs,3007,793,0.006416,0.011521
9,GWS,3005,1244,2069,5074,145,105,441,885,574,...,145,136,791,48,101,GWS,3005,791,0.006379,0.011370
10,Gold Coast,2990,1140,1864,4854,142,111,534,828,592,...,144,119,685,54,84,Gold Coast,2990,685,0.006101,0.003335
11,Fremantle,2975,1231,2124,5099,127,78,494,828,581,...,176,142,718,50,85,Fremantle,2975,718,0.005822,0.005836
12,Sydney,2975,1116,2002,4977,128,105,463,936,629,...,151,122,741,47,82,Sydney,2975,741,0.005822,0.007580
13,Melbourne,2954,1212,2086,5040,155,114,572,748,527,...,162,155,727,24,108,Melbourne,2954,727,0.005433,0.006519
14,Essendon,2854,1121,2286,5140,136,101,447,841,554,...,135,141,708,99,93,Essendon,2854,708,0.003579,0.005078
15,North Melbourne,2832,1084,2269,5101,124,86,516,843,578,...,148,124,641,59,85,North Melbourne,2832,641,0.003171,0.000000
16,Hawthorn,2794,1122,2106,4900,147,89,499,816,529,...,142,131,758,40,99,Hawthorn,2794,758,0.002466,0.008868
17,Adelaide,2661,1006,2140,4801,116,100,536,905,581,...,150,97,641,36,71,Adelaide,2661,641,0.000000,0.000000
18,Totals,56591,22721,39236,95827,2836,2064,9586,16365,10302,...,2956,2725,13834,1023,1882,Totals,56591,13834,1.000000,1.000000

In [30]:
df['Team'] = df['Team Totals For��']

In [31]:
df.columns

Index(['Team Totals For��', 'KI�?', 'MK��', 'HB��', 'DI��', 'GL��', 'BH��',
       'HO��', 'TK��', 'RB��', 'IF��', 'CL��', 'CG��', 'FF��', 'BR��', 'CP��',
       'UP��', 'CM��', 'MI��', '1%��', 'BO��', 'GA��', 'Team', 'kicks', '1%s',
       'kicks_normalised', '1%s_normalised'],
      dtype='object')

In [32]:
TEAM_COLUMN = 'Team'
KICK_STAT_COLUMN = 'KI�?'
ONE_PERCENTER_STAT_COLUMN = '1%s'

KICK_COLUMN_TO_BE_ADDED = 'kicks'
ONE_PERCENTER_COLUMN_TO_BE_ADDED = 'one-percenters'
def add_team_stats_to_afl_win_loss(df_team_stats, df_win_loss, column):
    for index, row in df_team_stats.iterrows():
        mask = df_win_loss[column] == row[TEAM_COLUMN]
        df_win_loss.loc[mask, KICK_COLUMN_TO_BE_ADDED + '_' + column] = row[KICK_STAT_COLUMN]
        df_win_loss.loc[mask, ONE_PERCENTER_COLUMN_TO_BE_ADDED + '_' + column] = row[ONE_PERCENTER_STAT_COLUMN]
    return df_win_loss

In [33]:
df_new = add_team_stats_to_afl_win_loss(df, df_team, 'home_team')

In [34]:
df_new = add_team_stats_to_afl_win_loss(df, df_team, 'away_team')

In [35]:
df_new

,Date,Home V Away,Venue,Crowd,Result,Disposals,Goals,score_home,score_away,home_team,away_team,home_win_lose,away_win_lose,kicks_home_team,one-percenters_home_team,kicks_away_team,one-percenters_away_team
0,Â Thu 19 Mar 7:40pm,RichmondÂ vÂ Carlton,MCG,NaN,105-81,P. CrippsÂ 31,J. MartinÂ 4,105,81,Richmond,Carlton,1,0,3587.0,862.0,3071.0,719.0
1,Â Fri 20 Mar 7:50pm,Western BulldogsÂ vÂ Collingwood,Marvel Stadium,NaN,34-86,C. MayneÂ 29,B. MihocekÂ 3,34,86,Western Bulldogs,Collingwood,0,1,3007.0,793.0,3301.0,819.0
2,Â Sat 21 Mar 2:10pm,EssendonÂ vÂ Fremantle,Marvel Stadium,NaN,63-57,D. ShielÂ 35,J. TownsendÂ 3,63,57,Essendon,Fremantle,1,0,2854.0,708.0,2975.0,718.0
3,Â Sat 21 Mar 4:35pm,AdelaideÂ vÂ Sydney,Adelaide Oval,NaN,71-74,L. ParkerÂ 30,I. HeeneyÂ 4,71,74,Adelaide,Sydney,0,1,2661.0,641.0,2975.0,741.0
4,Â Sat 21 Mar 6:40pm,Gold CoastÂ vÂ Port Adelaide,Metricon Stadium,NaN,29-76,T. RockliffÂ 26,S. MotlopÂ 2,29,76,Gold Coast,Port Adelaide,0,1,2990.0,685.0,3444.0,872.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Â Sat 19 Sep 7:40pm,BrisbaneÂ vÂ Carlton,Gabba,NaN,78-61,S. WalshÂ 31,H. McKayÂ 3,78,61,Brisbane,Carlton,1,0,3444.0,801.0,3071.0,719.0
149,Â Sun 20 Sep 12:35pm,HawthornÂ vÂ Gold Coast,Adelaide Oval,NaN,108-57,T. MitchellÂ 34,J. GunstonÂ 4,108,57,Hawthorn,Gold Coast,1,0,2794.0,758.0,2990.0,685.0
150,Â Sun 20 Sep 3:35pm,SydneyÂ vÂ Geelong,Metricon Stadium,NaN,63-69,J. LloydÂ 27,P. DangerfieldÂ 3,63,69,Sydney,Geelong,0,1,2975.0,741.0,3976.0,897.0
151,Â Sun 20 Sep 6:10pm,FremantleÂ vÂ Western Bulldogs,Cazaly's Stadium,NaN,44-74,L. HunterÂ 35,T. EnglishÂ 2,44,74,Fremantle,Western Bulldogs,0,1,2975.0,718.0,3007.0,793.0
152,Â Mon 21 Sep 7:15pm,CollingwoodÂ vÂ Port Adelaide,Gabba,NaN,45-61,T. RockliffÂ 30,B. MihocekÂ 2,45,61,Collingwood,Port Adelaide,0,1,3301.0,819.0,3444.0,872.0

In [36]:
df

,Team Totals For��,KI�?,MK��,HB��,DI��,GL��,BH��,HO��,TK��,RB��,...,CM��,MI��,1%��,BO��,GA��,Team,kicks,1%s,kicks_normalised,1%s_normalised
0,Geelong,3976,1757,2542,6518,220,146,626,1092,625,...,190,224,897,42,169,Geelong,3976,897,0.024383,0.019404
1,Richmond,3587,1437,2507,6094,202,133,557,1077,650,...,184,202,862,130,138,Richmond,3587,862,0.017170,0.016751
2,Brisbane,3444,1437,1865,5309,181,175,584,986,590,...,188,184,801,30,114,Brisbane,3444,801,0.014519,0.012128
3,Port Adelaide,3444,1260,2421,5865,183,151,567,1086,537,...,171,161,872,46,122,Port Adelaide,3444,872,0.014519,0.017509
4,St Kilda,3438,1427,2118,5556,187,123,612,904,589,...,182,175,764,92,113,St Kilda,3438,764,0.014408,0.009323
5,Collingwood,3301,1345,2684,5985,156,98,688,967,520,...,167,133,819,52,101,Collingwood,3301,819,0.011867,0.013492
6,West Coast,3283,1418,1871,5154,173,107,636,820,584,...,190,161,897,50,114,West Coast,3283,897,0.011533,0.019404
7,Carlton,3071,1200,1710,4781,146,114,478,899,529,...,171,149,719,56,94,Carlton,3071,719,0.007602,0.005912
8,Western Bulldogs,3007,1164,2572,5579,168,128,336,904,533,...,160,169,793,68,109,Western Bulldogs,3007,793,0.006416,0.011521
9,GWS,3005,1244,2069,5074,145,105,441,885,574,...,145,136,791,48,101,GWS,3005,791,0.006379,0.011370
10,Gold Coast,2990,1140,1864,4854,142,111,534,828,592,...,144,119,685,54,84,Gold Coast,2990,685,0.006101,0.003335
11,Fremantle,2975,1231,2124,5099,127,78,494,828,581,...,176,142,718,50,85,Fremantle,2975,718,0.005822,0.005836
12,Sydney,2975,1116,2002,4977,128,105,463,936,629,...,151,122,741,47,82,Sydney,2975,741,0.005822,0.007580
13,Melbourne,2954,1212,2086,5040,155,114,572,748,527,...,162,155,727,24,108,Melbourne,2954,727,0.005433,0.006519
14,Essendon,2854,1121,2286,5140,136,101,447,841,554,...,135,141,708,99,93,Essendon,2854,708,0.003579,0.005078
15,North Melbourne,2832,1084,2269,5101,124,86,516,843,578,...,148,124,641,59,85,North Melbourne,2832,641,0.003171,0.000000
16,Hawthorn,2794,1122,2106,4900,147,89,499,816,529,...,142,131,758,40,99,Hawthorn,2794,758,0.002466,0.008868
17,Adelaide,2661,1006,2140,4801,116,100,536,905,581,...,150,97,641,36,71,Adelaide,2661,641,0.000000,0.000000
18,Totals,56591,22721,39236,95827,2836,2064,9586,16365,10302,...,2956,2725,13834,1023,1882,Totals,56591,13834,1.000000,1.000000

In [37]:
df

,Team Totals For��,KI�?,MK��,HB��,DI��,GL��,BH��,HO��,TK��,RB��,...,CM��,MI��,1%��,BO��,GA��,Team,kicks,1%s,kicks_normalised,1%s_normalised
0,Geelong,3976,1757,2542,6518,220,146,626,1092,625,...,190,224,897,42,169,Geelong,3976,897,0.024383,0.019404
1,Richmond,3587,1437,2507,6094,202,133,557,1077,650,...,184,202,862,130,138,Richmond,3587,862,0.017170,0.016751
2,Brisbane,3444,1437,1865,5309,181,175,584,986,590,...,188,184,801,30,114,Brisbane,3444,801,0.014519,0.012128
3,Port Adelaide,3444,1260,2421,5865,183,151,567,1086,537,...,171,161,872,46,122,Port Adelaide,3444,872,0.014519,0.017509
4,St Kilda,3438,1427,2118,5556,187,123,612,904,589,...,182,175,764,92,113,St Kilda,3438,764,0.014408,0.009323
5,Collingwood,3301,1345,2684,5985,156,98,688,967,520,...,167,133,819,52,101,Collingwood,3301,819,0.011867,0.013492
6,West Coast,3283,1418,1871,5154,173,107,636,820,584,...,190,161,897,50,114,West Coast,3283,897,0.011533,0.019404
7,Carlton,3071,1200,1710,4781,146,114,478,899,529,...,171,149,719,56,94,Carlton,3071,719,0.007602,0.005912
8,Western Bulldogs,3007,1164,2572,5579,168,128,336,904,533,...,160,169,793,68,109,Western Bulldogs,3007,793,0.006416,0.011521
9,GWS,3005,1244,2069,5074,145,105,441,885,574,...,145,136,791,48,101,GWS,3005,791,0.006379,0.011370
10,Gold Coast,2990,1140,1864,4854,142,111,534,828,592,...,144,119,685,54,84,Gold Coast,2990,685,0.006101,0.003335
11,Fremantle,2975,1231,2124,5099,127,78,494,828,581,...,176,142,718,50,85,Fremantle,2975,718,0.005822,0.005836
12,Sydney,2975,1116,2002,4977,128,105,463,936,629,...,151,122,741,47,82,Sydney,2975,741,0.005822,0.007580
13,Melbourne,2954,1212,2086,5040,155,114,572,748,527,...,162,155,727,24,108,Melbourne,2954,727,0.005433,0.006519
14,Essendon,2854,1121,2286,5140,136,101,447,841,554,...,135,141,708,99,93,Essendon,2854,708,0.003579,0.005078
15,North Melbourne,2832,1084,2269,5101,124,86,516,843,578,...,148,124,641,59,85,North Melbourne,2832,641,0.003171,0.000000
16,Hawthorn,2794,1122,2106,4900,147,89,499,816,529,...,142,131,758,40,99,Hawthorn,2794,758,0.002466,0.008868
17,Adelaide,2661,1006,2140,4801,116,100,536,905,581,...,150,97,641,36,71,Adelaide,2661,641,0.000000,0.000000
18,Totals,56591,22721,39236,95827,2836,2064,9586,16365,10302,...,2956,2725,13834,1023,1882,Totals,56591,13834,1.000000,1.000000

In [38]:
df_new.columns

Index(['Date ', 'Home V Away ', 'Venue ', 'Crowd ', 'Result', 'Disposals',
       'Goals', 'score_home', 'score_away', 'home_team', 'away_team',
       'home_win_lose', 'away_win_lose', 'kicks_home_team',
       'one-percenters_home_team', 'kicks_away_team',
       'one-percenters_away_team'],
      dtype='object')

In [40]:
df_new.corr()

,Crowd,score_home,score_away,home_win_lose,away_win_lose,kicks_home_team,one-percenters_home_team,kicks_away_team,one-percenters_away_team
Crowd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
score_home,NaN,1.000000,-0.254820,0.649602,-0.640640,0.329105,0.346084,-0.259778,-0.280343
score_away,NaN,-0.254820,1.000000,-0.656824,0.663306,-0.327224,-0.309183,0.245223,0.194095
home_win_lose,NaN,0.649602,-0.656824,1.000000,-0.973795,0.396426,0.461639,-0.269043,-0.242352
away_win_lose,NaN,-0.640640,0.663306,-0.973795,1.000000,-0.397543,-0.457679,0.263346,0.237538
kicks_home_team,NaN,0.329105,-0.327224,0.396426,-0.397543,1.000000,0.818009,-0.058689,-0.013512
one-percenters_home_team,NaN,0.346084,-0.309183,0.461639,-0.457679,0.818009,1.000000,-0.081458,-0.058843
kicks_away_team,NaN,-0.259778,0.245223,-0.269043,0.263346,-0.058689,-0.081458,1.000000,0.805290
one-percenters_away_team,NaN,-0.280343,0.194095,-0.242352,0.237538,-0.013512,-0.058843,0.805290,1.000000

In [39]:
df_new.to_csv('20210322 AFL_2020_team_stats_and_win_loss.csv', index=False)

In [133]:
df_fin = df_new[['kicks_home_team',
       'one-percenters_home_team', 'kicks_away_team',
       'one-percenters_away_team', 'home_win_lose', 'away_win_lose']]

In [134]:
df_fin.to_csv('20210322 AFL_2020_team_stats_and_win_loss_trimmed.csv', index=False)